# Generated by Django 4.0.3 on 2022-09-21 10:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 13, 21, 18, 317315)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 13, 21, 18, 301691)),
        ),
    ]
