# Generated by Django 4.0.3 on 2022-09-22 07:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_api', '0002_remove_message_slug_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='update_status',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 10, 17, 6, 556537)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 10, 17, 6, 556537)),
        ),
    ]
