# Generated by Django 4.0.3 on 2022-09-22 08:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_api', '0003_ticket_update_status_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='update_status',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 57, 12, 339621)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 11, 57, 12, 339621)),
        ),
    ]
